### PR TITLE
feat(android): implement native camera permission callback with PermissionListener

### PR DESCRIPTION
**Pull request by pushpender-singh-ap**
## 🎯 Overview
Implements proper native camera permission callback mechanism for Android to achieve feature parity with iOS. The `requestCameraPermission()` method now correctly resolves based on the user's actual permission response instead of immediately returning `false`.

### Android Native Module
- ✅ Implemented `PermissionListener` callback interface for handling permission results
- ✅ Added promise storage pattern to resolve based on user action (grant/deny)
- ✅ Switched from `ActivityCompat.requestPermissions()` to `PermissionAwareActivity.requestPermissions()`
- ✅ Added proper cleanup in `invalidate()` to prevent memory leaks
- ✅ Removed incorrect `BaseActivityEventListener` implementation that caused build failures

### Documentation
- ✅ Added comprehensive `hasCameraPermission()` API documentation
- ✅ Added comprehensive `requestCameraPermission()` API documentation  
- ✅ Added ~100 line permission handling example with check → request → handle flow
- ✅ Added Android API compatibility notes (API 23+)
- ✅ Moved "Native permission handling" from roadmap to "Recently Completed"

### Example App
- ✅ Removed `react-native-permissions` dependency usage from `App.tsx`
- ✅ Updated to use built-in `BarcodeScanner.hasCameraPermission()` and `BarcodeScanner.requestCameraPermission()`
- ✅ Refactored permission checking logic with proper error handling

### Implementation Pattern

**Before (Broken):**
```kotlin
// Promise resolved immediately with false
@ReactMethod
fun requestCameraPermission(promise: Promise) {
    ActivityCompat.requestPermissions(...)
    promise.resolve(false) // ❌ Doesn't wait for user response
}
```

**After (Fixed):**
```kotlin
private var permissionPromise: Promise? = null

private val permissionListener = PermissionListener { requestCode, permissions, grantResults ->
  if (requestCode == CAMERA_PERMISSION_REQUEST_CODE) {
    val permissionGranted = grantResults.isNotEmpty() && 
                             grantResults[0] == PackageManager.PERMISSION_GRANTED
    permissionPromise?.resolve(permissionGranted) // ✅ Resolves based on actual user response
    permissionPromise = null
    return@PermissionListener true
  }
  false
}

@ReactMethod
fun requestCameraPermission(promise: Promise) {
    val permissionAwareActivity = currentActivity as? PermissionAwareActivity
    if (permissionAwareActivity == null) {
        promise.resolve(false)
        return
    }
    
    permissionPromise = promise
    permissionAwareActivity.requestPermissions(
        arrayOf(Manifest.permission.CAMERA),
        CAMERA_PERMISSION_REQUEST_CODE,
        permissionListener
    )
}
```

### Key Benefits
- ✅ Promise resolves with actual user response (`true` if granted, `false` if denied)
- ✅ Works with React Native 0.81+ New Architecture (Turbo Modules)
- ✅ Compatible with Android API 23+
- ✅ No breaking changes to existing API
- ✅ Eliminates need for third-party permission libraries like `react-native-permissions`
- ✅ Proper memory management with cleanup in `invalidate()`

## 📱 Usage Example

```typescript
import { BarcodeScanner } from '@pushpendersingh/react-native-scanner';

const checkCameraPermission = async () => {
  try {
    // First check if permission is already granted
    const hasPermission = await BarcodeScanner.hasCameraPermission();
    
    if (hasPermission) {
      console.log('Camera permission already granted');
      return true;
    }
    
    // Request permission if not granted
    const granted = await BarcodeScanner.requestCameraPermission();
    
    if (granted) {
      console.log('Camera permission granted by user');
      return true;
    } else {
      console.log('Camera permission denied by user');
      return false;
    }
  } catch (error) {
    console.error('Error checking camera permission:', error);
    return false;
  }
};
```

### Build Verification
- ✅ Android build successful (`yarn android` passes)
- ✅ No Kotlin compilation errors
- ✅ No TypeScript/lint errors
- ✅ Verified on Android device (app installed and ran successfully)

### Manual Testing
- ✅ Permission dialog appears when `requestCameraPermission()` is called
- ✅ Promise resolves to `true` when user grants permission
- ✅ Promise resolves to `false` when user denies permission
- ✅ `hasCameraPermission()` correctly returns permission status

### Test Commands
```bash
# Build Android app
cd example && yarn android

# Lint check
yarn lint

# Type check
yarn typescript
```

## 🚀 Breaking Changes

**None.** This is a bug fix that makes the Android implementation work as originally intended.

### Migration Guide
No migration needed. If you were using `react-native-permissions` as a workaround, you can now remove it:

```typescript
// Before (workaround)
import { request, PERMISSIONS } from 'react-native-permissions';
const result = await request(PERMISSIONS.ANDROID.CAMERA);

// After (built-in)
import { BarcodeScanner } from '@pushpendersingh/react-native-scanner';
const granted = await BarcodeScanner.requestCameraPermission();
```

## 📄 Files Changed

- `android/src/main/java/com/reactnativescanner/ReactNativeScannerModule.kt` - Core implementation
- `README.md` - Added comprehensive documentation and examples
- `example/src/App.tsx` - Updated to use built-in permission methods
- `example/Podfile.lock` - CocoaPods dependency update (iOS)

## 📸 Related Issues

Fixes the issue where `requestCameraPermission()` on Android always returned `false` immediately instead of waiting for user response.

## ✅ Checklist

- [x] Code builds successfully on Android
- [x] Code builds successfully on iOS
- [x] Documentation updated in README.md
- [x] Example app updated to demonstrate the feature
- [x] No breaking changes introduced
- [x] Feature parity with iOS achieved
- [x] Proper error handling implemented
- [x] Memory leaks prevented with proper cleanup
- [x] Compatible with New Architecture

---

### CODE REVIEW

File: android/src/main/java/com/pushpendersingh/reactnativescanner/ReactNativeScannerModule.kt [hunk 1]
```diff
@@ -9,12 +10,30 @@ import com.facebook.react.bridge.ReactApplicationContext
...
   private val cameraManager: CameraManager = CameraManager(reactContext)
+  private var permissionPromise: Promise? = null
+  
+  private val permissionListener = PermissionListener { requestCode, permissions, grantResults ->
+    if (requestCode == CAMERA_PERMISSION_REQUEST_CODE) {
+      // Validate that we're handling the correct permission
+      val permissionGranted = permissions.isNotEmpty() &&
+                               permissions[0] == Manifest.permission.CAMERA &&
+                               grantResults.isNotEmpty() && 
+                               grantResults[0] == PackageManager.PERMISSION_GRANTED
```
[the remark this answers is not in the document]
Comment (pushpender-singh-ap) [reply android/src/main/java/com/pushpendersingh/reactnativescanner/ReactNativeScannerModule.kt:29]: It's not necessary.

File: android/src/main/java/com/pushpendersingh/reactnativescanner/ReactNativeScannerModule.kt [hunk 2]
```diff
@@ -109,19 +128,33 @@ class ReactNativeScannerModule(reactContext: ReactApplicationContext) :
...
+      // Request permission using PermissionAwareActivity
+      val permissionAwareActivity = currentActivity as? PermissionAwareActivity
+      if (permissionAwareActivity != null) {
+        permissionAwareActivity.requestPermissions(
+          arrayOf(Manifest.permission.CAMERA),
+          CAMERA_PERMISSION_REQUEST_CODE,
+          permissionListener
+        )
+      } else {
+        promise.reject("NO_PERMISSION_AWARE_ACTIVITY", "Current activity does not implement PermissionAwareActivity")
```
[the remark this answers is not in the document]
Comment (pushpender-singh-ap) [reply android/src/main/java/com/pushpendersingh/reactnativescanner/ReactNativeScannerModule.kt:152]: It's not necessary.
